### ISSUE TITLE
Wrong Version Number Installing Using PIP

### ISSUE THREAD

**Issue by ahmedyarub** [brandond/requests-negotiate-sspi#16]
Recent versions are tagged with version 0.0.0.0 when installed, which causes problems with dependency management. I'm using Python 3.6.6 x64. I rolled back to version 0.3.4 and it worked without any problem.

**Comment by brandond** [comment]
For some reason I wasn't aware that I needed to include setuptools-version-command as an install requirement. I'm not super well versed in setuptools internals, but apparently when installing from a .tar.gz it ignores the package metadata and re-runs setup from scratch, which fails if the tool is not available.

Fixed in 1e0bdca0d5c43a57b2fc1b53cea6fd45cbafd907.
